// AUTO-GENERATED by scripts/build-api-demo.mjs — do not edit by hand.
// Real measured readings (campaigns 03-07). Numbers are measured, never invented.
// Regenerate: node scripts/build-api-demo.mjs

export interface DemoTerm {
  term: string;
  slug: string;
  campaign: string;
  campaignTitle: string;
  domain: string;
  velocityIndex: number | null;
  adoptionStage: string | null;
  deltas: { d30: number | null; d90: number | null; yoy: number | null };
  sentiment: number | null;
  inflections: { date: string; z: number }[];
  coOccurrence: string[];
  featured: boolean;
}

export const API_DEMO_TERMS: DemoTerm[] = [
  {
    "term": "ceasefire",
    "slug": "ceasefire",
    "campaign": "06",
    "campaignTitle": "The Iran War",
    "domain": "STRATEGIC / TERMINATION",
    "velocityIndex": 100,
    "adoptionStage": "spreading",
    "deltas": {
      "d30": -2.4,
      "d90": 424.9,
      "yoy": 250.6
    },
    "sentiment": -3.48,
    "inflections": [
      {
        "date": "2026-04-15",
        "z": 3.37
      },
      {
        "date": "2026-04-05",
        "z": 2.02
      }
    ],
    "coOccurrence": [
      "MOU",
      "truce",
      "60 days",
      "negotiations"
    ],
    "featured": true
  },
  {
    "term": "obliterated",
    "slug": "obliterated",
    "campaign": "06",
    "campaignTitle": "The Iran War",
    "domain": "STRATEGIC / BATTLE DAMAGE",
    "velocityIndex": 0,
    "adoptionStage": "rising",
    "deltas": {
      "d30": -11.5,
      "d90": -63.4,
      "yoy": 135.5
    },
    "sentiment": null,
    "inflections": [
      {
        "date": "2026-02-25",
        "z": 5.43
      },
      {
        "date": "2026-03-12",
        "z": 2.06
      }
    ],
    "coOccurrence": [
      "Fordow",
      "damage assessment",
      "setback",
      "nuclear program"
    ],
    "featured": true
  },
  {
    "term": "debasement trade",
    "slug": "debasement-trade",
    "campaign": "07",
    "campaignTitle": "Money",
    "domain": "INSTITUTIONAL / THE BET",
    "velocityIndex": 100,
    "adoptionStage": "emerging",
    "deltas": {
      "d30": 374.2,
      "d90": -73.4,
      "yoy": null
    },
    "sentiment": -0.28,
    "inflections": [
      {
        "date": "2025-10-05",
        "z": 2.86
      },
      {
        "date": "2026-01-26",
        "z": 2.66
      },
      {
        "date": "2025-10-15",
        "z": 2.06
      }
    ],
    "coOccurrence": [
      "gold",
      "bitcoin",
      "fiscal",
      "unwind"
    ],
    "featured": true
  },
  {
    "term": "soft landing",
    "slug": "soft-landing",
    "campaign": "05",
    "campaignTitle": "The Economy",
    "domain": "MACRO OUTLOOK / INSTITUTIONAL",
    "velocityIndex": 12,
    "adoptionStage": "fading",
    "deltas": {
      "d30": -7.2,
      "d90": -48,
      "yoy": -35.6
    },
    "sentiment": -0.79,
    "inflections": [
      {
        "date": "2025-09-15",
        "z": 2.69
      },
      {
        "date": "2025-10-11",
        "z": 2.53
      },
      {
        "date": "2026-02-14",
        "z": 2.07
      }
    ],
    "coOccurrence": [
      "Fed",
      "rate cuts",
      "recession",
      "labor market",
      "no landing",
      "disinflation"
    ],
    "featured": true
  },
  {
    "term": "vibecession",
    "slug": "vibecession",
    "campaign": "05",
    "campaignTitle": "The Economy",
    "domain": "LIVED EXPERIENCE / SENTIMENT",
    "velocityIndex": 100,
    "adoptionStage": "spreading",
    "deltas": {
      "d30": 275,
      "d90": 188,
      "yoy": 617
    },
    "sentiment": -1.6,
    "inflections": [
      {
        "date": "2026-05-28",
        "z": 2.9
      }
    ],
    "coOccurrence": [
      "affordability",
      "real economy",
      "data vs vibes",
      "consumer sentiment",
      "soft landing",
      "groceries"
    ],
    "featured": true
  },
  {
    "term": "greedflation",
    "slug": "greedflation",
    "campaign": "05",
    "campaignTitle": "The Economy",
    "domain": "ATTRIBUTION / POPULIST",
    "velocityIndex": 0,
    "adoptionStage": "declining",
    "deltas": {
      "d30": -41,
      "d90": -58,
      "yoy": -86
    },
    "sentiment": -2.4,
    "inflections": [
      {
        "date": "2025-07-12",
        "z": 2.5
      }
    ],
    "coOccurrence": [
      "corporate profits",
      "price gouging",
      "margins",
      "shrinkflation",
      "record profits"
    ],
    "featured": true
  },
  {
    "term": "America First",
    "slug": "america-first",
    "campaign": "06",
    "campaignTitle": "The Iran War",
    "domain": "ATTRIBUTION / CONTESTED CREED",
    "velocityIndex": 25,
    "adoptionStage": "contested",
    "deltas": {
      "d30": -15.4,
      "d90": -54.8,
      "yoy": -11.3
    },
    "sentiment": -1.75,
    "inflections": [
      {
        "date": "2026-02-25",
        "z": 4.07
      }
    ],
    "coOccurrence": [
      "restraint",
      "isolationism",
      "intervention",
      "base"
    ],
    "featured": true
  },
  {
    "term": "MAGA Warrior",
    "slug": "maga-warrior",
    "campaign": "04",
    "campaignTitle": "Primaries",
    "domain": "LOYALTY COMMS / GOP PRIMARY",
    "velocityIndex": 50,
    "adoptionStage": "rising",
    "deltas": {
      "d30": 613,
      "d90": 290.6,
      "yoy": 704.3
    },
    "sentiment": null,
    "inflections": [
      {
        "date": "2026-03-02",
        "z": 4.26
      },
      {
        "date": "2026-05-16",
        "z": 3.14
      }
    ],
    "coOccurrence": [
      "endorsement",
      "fighter",
      "totally reliable",
      "America First",
      "loyal",
      "real Republican"
    ],
    "featured": true
  },
  {
    "term": "seed oils",
    "slug": "seed-oils",
    "campaign": "03",
    "campaignTitle": "Bodies and Food",
    "domain": "WELLNESS / FUNCTIONAL MEDICINE",
    "velocityIndex": 0,
    "adoptionStage": "fading",
    "deltas": {
      "d30": -9.8,
      "d90": 87.9,
      "yoy": -39.8
    },
    "sentiment": 0.63,
    "inflections": [
      {
        "date": "2026-02-10",
        "z": 7.08
      }
    ],
    "coOccurrence": [
      "tallow",
      "ghee",
      "inflammation",
      "omega-6",
      "refined",
      "industrial",
      "ancestral"
    ],
    "featured": true
  },
  {
    "term": "body neutrality",
    "slug": "body-neutrality",
    "campaign": "03",
    "campaignTitle": "Bodies and Food",
    "domain": "CONSUMER IDENTITY / SUCCESSOR",
    "velocityIndex": 80,
    "adoptionStage": "contested",
    "deltas": {
      "d30": -20,
      "d90": 78.4,
      "yoy": 1.6
    },
    "sentiment": null,
    "inflections": [
      {
        "date": "2025-10-16",
        "z": 6.28
      }
    ],
    "coOccurrence": [
      "body positivity",
      "self-image",
      "intuitive eating",
      "mental health",
      "neutral",
      "peace"
    ],
    "featured": false
  },
  {
    "term": "chronic disease epidemic",
    "slug": "chronic-disease-epidemic",
    "campaign": "03",
    "campaignTitle": "Bodies and Food",
    "domain": "FEDERAL HEALTH COMMS",
    "velocityIndex": 100,
    "adoptionStage": "fading",
    "deltas": {
      "d30": 177.9,
      "d90": 19.2,
      "yoy": -57.2
    },
    "sentiment": -0.42,
    "inflections": [
      {
        "date": "2025-05-27",
        "z": 2.94
      },
      {
        "date": "2025-03-30",
        "z": 2.81
      },
      {
        "date": "2025-09-11",
        "z": 2.29
      }
    ],
    "coOccurrence": [
      "metabolic",
      "autoimmune",
      "childhood",
      "preventable",
      "root cause",
      "lifestyle"
    ],
    "featured": false
  },
  {
    "term": "evidence-based",
    "slug": "evidence-based",
    "campaign": "03",
    "campaignTitle": "Bodies and Food",
    "domain": "GATEKEEPING / AUTHORITY",
    "velocityIndex": 60,
    "adoptionStage": "contested",
    "deltas": {
      "d30": 6.4,
      "d90": -7.2,
      "yoy": 28.7
    },
    "sentiment": 0.32,
    "inflections": [
      {
        "date": "2026-01-05",
        "z": 2.67
      },
      {
        "date": "2025-12-14",
        "z": 2.11
      },
      {
        "date": "2025-08-25",
        "z": 2
      }
    ],
    "coOccurrence": [
      "randomized controlled trial",
      "peer-reviewed",
      "meta-analysis",
      "guidelines",
      "standard of care",
      "rigorous"
    ],
    "featured": false
  },
  {
    "term": "food noise",
    "slug": "food-noise",
    "campaign": "03",
    "campaignTitle": "Bodies and Food",
    "domain": "PATIENT / USER (ENDOGENOUS)",
    "velocityIndex": 20,
    "adoptionStage": "rising",
    "deltas": {
      "d30": -21.4,
      "d90": 89.6,
      "yoy": 262.5
    },
    "sentiment": null,
    "inflections": [
      {
        "date": "2026-02-11",
        "z": 4.77
      },
      {
        "date": "2026-01-31",
        "z": 3.01
      },
      {
        "date": "2025-06-02",
        "z": 2.13
      }
    ],
    "coOccurrence": [
      "appetite",
      "intrusive",
      "quiet",
      "relief",
      "cravings",
      "brain",
      "switched off"
    ],
    "featured": false
  },
  {
    "term": "weight management",
    "slug": "weight-management",
    "campaign": "03",
    "campaignTitle": "Bodies and Food",
    "domain": "SOFT CLINICAL / MARKETING",
    "velocityIndex": 40,
    "adoptionStage": "contested",
    "deltas": {
      "d30": -25.7,
      "d90": -12.4,
      "yoy": -28.4
    },
    "sentiment": null,
    "inflections": [
      {
        "date": "2025-12-03",
        "z": 3.45
      },
      {
        "date": "2026-02-20",
        "z": 2.22
      },
      {
        "date": "2025-09-30",
        "z": 2.2
      }
    ],
    "coOccurrence": [
      "lifestyle",
      "behavior",
      "program",
      "sustainable",
      "holistic",
      "journey"
    ],
    "featured": false
  },
  {
    "term": "battleground",
    "slug": "battleground",
    "campaign": "04",
    "campaignTitle": "Primaries",
    "domain": "STRATEGIC MAPPING",
    "velocityIndex": 25,
    "adoptionStage": "contested",
    "deltas": {
      "d30": -7.6,
      "d90": 6.2,
      "yoy": -22.7
    },
    "sentiment": -2.26,
    "inflections": [
      {
        "date": "2025-05-01",
        "z": 4.36
      },
      {
        "date": "2025-12-07",
        "z": 2.71
      },
      {
        "date": "2025-08-08",
        "z": 2.27
      }
    ],
    "coOccurrence": [
      "swing state",
      "toss-up",
      "lean",
      "persuadable",
      "margin",
      "suburban"
    ],
    "featured": false
  },
  {
    "term": "endorsement machine",
    "slug": "endorsement-machine",
    "campaign": "04",
    "campaignTitle": "Primaries",
    "domain": "PRIMARY MECHANICS / PRESS",
    "velocityIndex": 100,
    "adoptionStage": "rising",
    "deltas": {
      "d30": 173.7,
      "d90": 6.1,
      "yoy": 126.1
    },
    "sentiment": null,
    "inflections": [
      {
        "date": "2025-12-14",
        "z": 4.51
      },
      {
        "date": "2026-05-14",
        "z": 2.76
      },
      {
        "date": "2025-08-12",
        "z": 2.29
      }
    ],
    "coOccurrence": [
      "hand-picked",
      "scorecard",
      "win rate",
      "primary cycle",
      "hold the line",
      "backed"
    ],
    "featured": false
  },
  {
    "term": "open seat",
    "slug": "open-seat",
    "campaign": "04",
    "campaignTitle": "Primaries",
    "domain": "ELECTION MECHANICS",
    "velocityIndex": 75,
    "adoptionStage": "rising",
    "deltas": {
      "d30": 94.6,
      "d90": 45.9,
      "yoy": 75.2
    },
    "sentiment": 0.14,
    "inflections": [
      {
        "date": "2026-05-17",
        "z": 3.49
      },
      {
        "date": "2025-07-24",
        "z": 2.95
      },
      {
        "date": "2025-10-26",
        "z": 2.02
      }
    ],
    "coOccurrence": [
      "retirement",
      "term-limited",
      "vacancy",
      "pickup opportunity",
      "recruitment",
      "no incumbent"
    ],
    "featured": false
  },
  {
    "term": "affordability",
    "slug": "affordability",
    "campaign": "05",
    "campaignTitle": "The Economy",
    "domain": "LIVED EXPERIENCE / LEVEL",
    "velocityIndex": 62,
    "adoptionStage": "rising",
    "deltas": {
      "d30": 9,
      "d90": -6.8,
      "yoy": 99.8
    },
    "sentiment": -0.54,
    "inflections": [
      {
        "date": "2026-02-22",
        "z": 2.6
      },
      {
        "date": "2025-12-07",
        "z": 2.1
      }
    ],
    "coOccurrence": [
      "cost of living",
      "prices",
      "wages",
      "rent",
      "groceries",
      "squeeze",
      "still high"
    ],
    "featured": false
  },
  {
    "term": "are you better off",
    "slug": "are-you-better-off",
    "campaign": "05",
    "campaignTitle": "The Economy",
    "domain": "MOBILIZATION / CYCLICAL",
    "velocityIndex": 88,
    "adoptionStage": "rising",
    "deltas": {
      "d30": 81,
      "d90": 10.5,
      "yoy": 56.2
    },
    "sentiment": null,
    "inflections": [
      {
        "date": "2025-08-08",
        "z": 4.89
      },
      {
        "date": "2025-12-07",
        "z": 3.22
      },
      {
        "date": "2025-07-11",
        "z": 2.19
      }
    ],
    "coOccurrence": [
      "four years ago",
      "midterms",
      "kitchen table",
      "referendum",
      "worse off",
      "your wallet"
    ],
    "featured": false
  },
  {
    "term": "higher for longer",
    "slug": "higher-for-longer",
    "campaign": "05",
    "campaignTitle": "The Economy",
    "domain": "MACRO / RATES",
    "velocityIndex": 50,
    "adoptionStage": "rising",
    "deltas": {
      "d30": -19.8,
      "d90": 115.8,
      "yoy": 293.6
    },
    "sentiment": -1.34,
    "inflections": [
      {
        "date": "2026-03-09",
        "z": 2.88
      },
      {
        "date": "2026-03-29",
        "z": 2.21
      },
      {
        "date": "2026-03-19",
        "z": 2.19
      }
    ],
    "coOccurrence": [
      "rate cuts",
      "restrictive",
      "terminal rate",
      "hawkish",
      "2 percent",
      "policy path"
    ],
    "featured": false
  },
  {
    "term": "junk fees",
    "slug": "junk-fees",
    "campaign": "05",
    "campaignTitle": "The Economy",
    "domain": "REGULATORY / CONSUMER",
    "velocityIndex": 38,
    "adoptionStage": "declining",
    "deltas": {
      "d30": -33.5,
      "d90": -30.8,
      "yoy": -79.1
    },
    "sentiment": null,
    "inflections": [
      {
        "date": "2025-05-09",
        "z": 4.18
      },
      {
        "date": "2025-10-01",
        "z": 2.76
      },
      {
        "date": "2025-09-16",
        "z": 2.21
      }
    ],
    "coOccurrence": [
      "hidden fees",
      "drip pricing",
      "all-in pricing",
      "surcharge",
      "resort fee",
      "transparency"
    ],
    "featured": false
  },
  {
    "term": "price gouging",
    "slug": "price-gouging",
    "campaign": "05",
    "campaignTitle": "The Economy",
    "domain": "MORAL-LEGAL / POPULIST",
    "velocityIndex": 25,
    "adoptionStage": "rising",
    "deltas": {
      "d30": 18.1,
      "d90": 92.1,
      "yoy": 88.5
    },
    "sentiment": -1.79,
    "inflections": [
      {
        "date": "2026-03-17",
        "z": 2.65
      },
      {
        "date": "2026-03-27",
        "z": 2.55
      },
      {
        "date": "2026-03-07",
        "z": 2.39
      }
    ],
    "coOccurrence": [
      "gouging",
      "shortage",
      "emergency",
      "groceries",
      "windfall",
      "crackdown"
    ],
    "featured": false
  },
  {
    "term": "real wages",
    "slug": "real-wages",
    "campaign": "05",
    "campaignTitle": "The Economy",
    "domain": "MACRO / LABOR",
    "velocityIndex": 75,
    "adoptionStage": "contested",
    "deltas": {
      "d30": 90.3,
      "d90": -28.7,
      "yoy": 20
    },
    "sentiment": -1.78,
    "inflections": [
      {
        "date": "2025-08-04",
        "z": 2.59
      },
      {
        "date": "2026-02-18",
        "z": 2.29
      },
      {
        "date": "2025-05-05",
        "z": 2.26
      }
    ],
    "coOccurrence": [
      "inflation-adjusted",
      "median",
      "purchasing power",
      "earnings",
      "compensation",
      "CPI"
    ],
    "featured": false
  },
  {
    "term": "boots on the ground",
    "slug": "boots-on-the-ground",
    "campaign": "06",
    "campaignTitle": "The Iran War",
    "domain": "LIVED EXPERIENCE / COMMITMENT",
    "velocityIndex": 38,
    "adoptionStage": "contested",
    "deltas": {
      "d30": 14.5,
      "d90": -55.9,
      "yoy": 20.6
    },
    "sentiment": -1.12,
    "inflections": [
      {
        "date": "2026-01-01",
        "z": 3.45
      },
      {
        "date": "2026-02-28",
        "z": 2.71
      }
    ],
    "coOccurrence": [
      "air strikes",
      "ground troops",
      "quagmire",
      "no boots"
    ],
    "featured": false
  },
  {
    "term": "breakout",
    "slug": "breakout",
    "campaign": "06",
    "campaignTitle": "The Iran War",
    "domain": "STRATEGIC / NUCLEAR TIMELINE",
    "velocityIndex": 88,
    "adoptionStage": "rising",
    "deltas": {
      "d30": -12.5,
      "d90": 31.2,
      "yoy": 74.2
    },
    "sentiment": null,
    "inflections": [
      {
        "date": "2026-04-20",
        "z": 2.99
      },
      {
        "date": "2026-03-25",
        "z": 2.17
      },
      {
        "date": "2026-04-10",
        "z": 2.04
      }
    ],
    "coOccurrence": [
      "enrichment",
      "uranium",
      "IAEA",
      "timeline"
    ],
    "featured": false
  },
  {
    "term": "de-escalation",
    "slug": "de-escalation",
    "campaign": "06",
    "campaignTitle": "The Iran War",
    "domain": "STRATEGIC / OFF-RAMP",
    "velocityIndex": 50,
    "adoptionStage": "contested",
    "deltas": {
      "d30": -1.3,
      "d90": 7.2,
      "yoy": -2.1
    },
    "sentiment": null,
    "inflections": [
      {
        "date": "2026-04-08",
        "z": 2.45
      },
      {
        "date": "2026-03-29",
        "z": 2.42
      },
      {
        "date": "2026-02-26",
        "z": 2.34
      }
    ],
    "coOccurrence": [
      "off-ramp",
      "diplomacy",
      "escalation",
      "restraint"
    ],
    "featured": false
  },
  {
    "term": "mission accomplished",
    "slug": "mission-accomplished",
    "campaign": "06",
    "campaignTitle": "The Iran War",
    "domain": "ATTRIBUTION / PREMATURE-VICTORY ECHO",
    "velocityIndex": 75,
    "adoptionStage": "contested",
    "deltas": {
      "d30": 20.7,
      "d90": -20,
      "yoy": -6.9
    },
    "sentiment": null,
    "inflections": [
      {
        "date": "2025-08-13",
        "z": 5.56
      },
      {
        "date": "2026-04-04",
        "z": 2.03
      }
    ],
    "coOccurrence": [
      "premature",
      "declared victory",
      "hubris",
      "Iraq"
    ],
    "featured": false
  },
  {
    "term": "peace through strength",
    "slug": "peace-through-strength",
    "campaign": "06",
    "campaignTitle": "The Iran War",
    "domain": "ATTRIBUTION / VICTORY FRAME",
    "velocityIndex": 62,
    "adoptionStage": "fading",
    "deltas": {
      "d30": 37.1,
      "d90": -52.8,
      "yoy": -51.7
    },
    "sentiment": null,
    "inflections": [
      {
        "date": "2026-01-05",
        "z": 3.24
      },
      {
        "date": "2025-12-03",
        "z": 3.19
      },
      {
        "date": "2026-02-27",
        "z": 2.17
      }
    ],
    "coOccurrence": [
      "deterrence",
      "ceasefire",
      "strength",
      "doctrine"
    ],
    "featured": false
  },
  {
    "term": "regime change",
    "slug": "regime-change",
    "campaign": "06",
    "campaignTitle": "The Iran War",
    "domain": "STRATEGIC / WAR AIM",
    "velocityIndex": 12,
    "adoptionStage": "rising",
    "deltas": {
      "d30": -9.2,
      "d90": -51.1,
      "yoy": 250
    },
    "sentiment": -3.46,
    "inflections": [
      {
        "date": "2026-02-25",
        "z": 2.65
      },
      {
        "date": "2026-03-07",
        "z": 2.37
      }
    ],
    "coOccurrence": [
      "sovereignty",
      "war aim",
      "Tehran",
      "nation building"
    ],
    "featured": false
  },
  {
    "term": "digital gold",
    "slug": "digital-gold",
    "campaign": "07",
    "campaignTitle": "Money",
    "domain": "LIVED EXPERIENCE / THE PITCH",
    "velocityIndex": 29,
    "adoptionStage": "contested",
    "deltas": {
      "d30": 15.9,
      "d90": -42.9,
      "yoy": 4.6
    },
    "sentiment": null,
    "inflections": [
      {
        "date": "2025-09-03",
        "z": 3.29
      },
      {
        "date": "2026-02-25",
        "z": 2.9
      },
      {
        "date": "2026-02-02",
        "z": 2.55
      }
    ],
    "coOccurrence": [
      "gold",
      "scarcity",
      "hedge",
      "halving"
    ],
    "featured": false
  },
  {
    "term": "fiscal dominance",
    "slug": "fiscal-dominance",
    "campaign": "07",
    "campaignTitle": "Money",
    "domain": "INSTITUTIONAL / THE DIAGNOSIS",
    "velocityIndex": 71,
    "adoptionStage": "spreading",
    "deltas": {
      "d30": -29.4,
      "d90": -35.5,
      "yoy": 300
    },
    "sentiment": null,
    "inflections": [
      {
        "date": "2026-01-03",
        "z": 2.47
      },
      {
        "date": "2025-08-29",
        "z": 2.39
      },
      {
        "date": "2026-02-07",
        "z": 2.2
      }
    ],
    "coOccurrence": [
      "deficit",
      "debt",
      "Fed independence",
      "yields"
    ],
    "featured": false
  },
  {
    "term": "hard money",
    "slug": "hard-money",
    "campaign": "07",
    "campaignTitle": "Money",
    "domain": "ATTRIBUTION / THE VIRTUE",
    "velocityIndex": 86,
    "adoptionStage": "spreading",
    "deltas": {
      "d30": 49.5,
      "d90": 88.6,
      "yoy": 199
    },
    "sentiment": null,
    "inflections": [
      {
        "date": "2025-10-02",
        "z": 6.22
      },
      {
        "date": "2026-06-02",
        "z": 2.02
      }
    ],
    "coOccurrence": [
      "scarcity",
      "gold",
      "discipline",
      "deflation"
    ],
    "featured": false
  },
  {
    "term": "inflation hedge",
    "slug": "inflation-hedge",
    "campaign": "07",
    "campaignTitle": "Money",
    "domain": "LIVED EXPERIENCE / PROTECTION",
    "velocityIndex": 14,
    "adoptionStage": "fading",
    "deltas": {
      "d30": -44.7,
      "d90": -0.5,
      "yoy": -38.9
    },
    "sentiment": null,
    "inflections": [
      {
        "date": "2025-10-09",
        "z": 3.12
      },
      {
        "date": "2025-06-07",
        "z": 3.09
      },
      {
        "date": "2025-10-19",
        "z": 2.78
      }
    ],
    "coOccurrence": [
      "gold",
      "bitcoin",
      "real assets",
      "CPI"
    ],
    "featured": false
  },
  {
    "term": "magic internet money",
    "slug": "magic-internet-money",
    "campaign": "07",
    "campaignTitle": "Money",
    "domain": "ATTRIBUTION / THE DISMISSAL",
    "velocityIndex": 0,
    "adoptionStage": "dormant",
    "deltas": {
      "d30": -100,
      "d90": -79.8,
      "yoy": -100
    },
    "sentiment": 0.08,
    "inflections": [
      {
        "date": "2025-12-08",
        "z": 2.48
      },
      {
        "date": "2026-02-22",
        "z": 2.3
      },
      {
        "date": "2026-06-24",
        "z": 2.27
      }
    ],
    "coOccurrence": [
      "scam",
      "HODL",
      "irony",
      "speculation"
    ],
    "featured": false
  },
  {
    "term": "sound money",
    "slug": "sound-money",
    "campaign": "07",
    "campaignTitle": "Money",
    "domain": "ATTRIBUTION / THE CREED",
    "velocityIndex": 57,
    "adoptionStage": "fading",
    "deltas": {
      "d30": 52.5,
      "d90": -15.8,
      "yoy": -46
    },
    "sentiment": null,
    "inflections": [
      {
        "date": "2025-10-02",
        "z": 5.05
      },
      {
        "date": "2025-05-27",
        "z": 4.01
      }
    ],
    "coOccurrence": [
      "gold standard",
      "bitcoin",
      "discipline",
      "fiat"
    ],
    "featured": false
  },
  {
    "term": "store of value",
    "slug": "store-of-value",
    "campaign": "07",
    "campaignTitle": "Money",
    "domain": "LIVED EXPERIENCE / SAVINGS",
    "velocityIndex": 43,
    "adoptionStage": "contested",
    "deltas": {
      "d30": 23.3,
      "d90": -42.4,
      "yoy": -20.2
    },
    "sentiment": 0.89,
    "inflections": [
      {
        "date": "2026-02-05",
        "z": 2.42
      },
      {
        "date": "2025-10-17",
        "z": 2.36
      },
      {
        "date": "2025-10-05",
        "z": 2.35
      }
    ],
    "coOccurrence": [
      "gold",
      "bitcoin",
      "inflation",
      "savings"
    ],
    "featured": false
  }
];
